{% set name = "hendrics" %}
{% set version = "8.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hendrics-{{ version }}.tar.gz
  sha256: 42745c8b6a9b16199b1e30bfac4a2dfbc435f4e8be7444ac278fc749d79f10f9

build:
  number: 0
  noarch: python
  entry_points:
    - HEN2xspec = hendrics.save_as_xspec:main
    - HENaccelsearch = hendrics.efsearch:main_accelsearch
    - HENbaseline = hendrics.lcurve:baseline_main
    - HENbinary = hendrics.binary:main_presto
    - HENcalibrate = hendrics.calibrate:main
    - HENcolors = hendrics.colors:main
    - HENcreategti = hendrics.create_gti:main
    - HENdeorbit = hendrics.fold:main_deorbit
    - HENdumpdyn = hendrics.fspec:dumpdyn_main
    - HENefsearch = hendrics.efsearch:main_efsearch
    - HENexcvar = hendrics.exvar:main
    - HENexposure = hendrics.exposure:main
    - HENfake = hendrics.fake:main
    - HENfold = hendrics.fold:main_fold
    - HENfspec = hendrics.fspec:main
    - HENjoinevents = hendrics.read_events:main_join
    - HENlags = hendrics.timelags:main
    - HENlcurve = hendrics.lcurve:main
    - HENmodel = hendrics.modeling:main_model
    - HENphaseogram = hendrics.phaseogram:main_phaseogram
    - HENphasetag = hendrics.phasetag:main_phasetag
    - HENplot = hendrics.plot:main
    - HENreadevents = hendrics.read_events:main
    - HENreadfile = hendrics.io:main
    - HENrebin = hendrics.rebin:main
    - HENscramble = hendrics.fake:main_scramble
    - HENscrunchlc = hendrics.lcurve:scrunch_main
    - HENsplitevents = hendrics.read_events:main_splitevents
    - HENsumfspec = hendrics.sum_fspec:main
    - HENvarenergy = hendrics.varenergy:main
    - HENz2vspf = hendrics.efsearch:main_z2vspf
    - HENzsearch = hendrics.efsearch:main_zsearch
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - astropy >=4.0
    - matplotlib-base
    - numpy
    - scipy
    - stingray >=1.0
    - tqdm

test:
  imports:
    - hendrics
    - hendrics.compat
  commands:
    - pip check
    - HEN2xspec --help
    - HENaccelsearch --help
    - HENbaseline --help
    - HENbinary --help
    - HENcalibrate --help
    - HENcolors --help
    - HENcreategti --help
    - HENdeorbit --help
    - HENdumpdyn --help
    - HENefsearch --help
    - HENexcvar --help
    - HENexposure --help
    - HENfake --help
    - HENfold --help
    - HENfspec --help
    - HENjoinevents --help
    - HENlags --help
    - HENlcurve --help
    - HENmodel --help
    - HENphaseogram --help
    - HENphasetag --help
    - HENplot --help
    - HENreadevents --help
    - HENreadfile --help
    - HENrebin --help
    - HENscramble --help
    - HENscrunchlc --help
    - HENsplitevents --help
    - HENsumfspec --help
    - HENvarenergy --help
    - HENz2vspf --help
    - HENzsearch --help
  requires:
    - pip

about:
  home: http://github.com/StingraySoftware/hendrics
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: High-ENergy Data Reduction Interface from the Command Shell
  description: |
    This Astropy-affiliated software package is designed
    to do correctly and fairly easily a **quick-look (spectral-) timing
    analysis** of X-ray data, including most of the functionality implemented
    in stingray (github.com/stingraysoftware/stingray), but from the command line,
    starting from mission-specific event files (NuSTAR, RXTE, XMM, and more).
  doc_url: http://hendrics.readthedocs.io/
  dev_url: https://github.com/StingraySoftware/hendrics

extra:
  recipe-maintainers:
    - matteobachetti
    - dhuppenkothen
    - evandromr
