{% set name = "hendrics" %}
{% set version = "6.0" %}
{% set sha256 = "bd10bb14c162a2242d8d74ac90d25883bd769131e135e446c18ef6a6c7d36f4f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - numpy >=1.16.0
  run:
    - python
    - astropy
    - scipy >=0.18.0
    - numpy >=1.16.0
    - numpy  # [py>=38]
    - matplotlib-base >=1.3
    - stingray >=0.3

test:
  imports:
    - hendrics

about:
  home: http://github.com/StingraySoftware/hendrics
  license: 3-clause BSD
  license_family: BSD
  license_file: LICENSE.rst
  summary: High-ENergy Data Reduction Interface from the Command Shell
  description: |
    This Astropy-affiliated software package is designed
    to do correctly and fairly easily a **quick-look (spectral-) timing
    analysis** of X-ray data, including most of the functionality implemented
    in stingray (github.com/stingraysoftware/stingray), but from the command line,
    starting from mission-specific event files (NuSTAR, RXTE, XMM, and more).
  doc_url: http://hendrics.readthedocs.io/
  dev_url: https://github.com/StingraySoftware/hendrics

extra:
  recipe-maintainers:
    - matteobachetti
    - dhuppenkothen
    - evandromr
