travis:
  secure:
    BINSTAR_TOKEN: XKBfH3NA+abLeZ0mJch2U21ICvOY9dzz873eW8m4qogAiJE7Q/LVjFTaPQ1KDbXihAC00ZAz+HXIOb8+c4NUIarXgjzmmmqeZUwAyL0f7uFgvs9snBoKsikhoKBj6ov45BogG7j5rUrCCnAMH0yvRSS6Nf8W3D5PSrVA7uHBtDr+rK2aX1G62j09Kp44XBqL/Vm26ezIOWmvIPq2lEraouOh5ZyNN6oHLkK90kxDzQ7UR98HaoJ/sVgyMx4wyWiR/BjVvz9vbPtzi6bzuRYUaqZrW3nrWymx9Lva3h+ECK+/hSrMIy5sPFAbCJ4cm6TAeXnYg7R+dQwsN6dv6AY6p7Gxbe18ZI50vhjjJ6GDTzEGrdt+JbI7fTrChOghRlA4xAxgrgP+jLhTaJD99vJP+/8U1oZ6KRyfMLGcMpQYPlnO6JZxOwMTrIcrdNAeEkhmlSqPfyC9e7z0fmwxEemZg5G0QMtMkpCl3mSwHa3No+f+9oszO8ngqtWMjRrZ9UP3LhItdgLm8a5Qx1zOyeSBb9XfHsvnRFN1CjmnSYQkqC1a1o8ePEJD/LlKhVyGViLreg25fYiijrTGTYH+uDa2tMKba8ZaJe3Ty0KWYXWE1wZ8BA2ryLWGpyMGYmyCYfvK5zl8WtB1KAWhbB1YgnZZdqjc+GilYwDfu1EhPaSOX1M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
