travis:
  secure:
    BINSTAR_TOKEN: mkWFh0VCCGbHWkNAgLyMKgCyLCurZBIlEz/Lt5OeMcht9CENgkSMQnE98GF/bJu3ay+uMP7FgvsQgV9XaHD9zu6gy2wk3SuTqSxJ3oGehp11Ag0WxK6KI/jw6GRe+QoFmFaaVLp1xAQGTXV/FS6bJi5L1rz4TnClpCFU9vld5wybMrrBzGbOaweMXdITEcMXoWoMiV1N6npmGIKGWa6ZYRa12M8C1xSpy4I9Qn9yaPai1K+SMcdegSorTlpGPxYDPumTvXtckbedZbm4YlorqHsVK+3Q7M4XlEoVqThCB7F3SKNYa4ZBzNUmvBMXBI3zV3W8YUxC1a7Wrc9LAQgqLopvgYZuwlRAKIT9txcm1JUSYEw6FE+xJZEMMycit3OP6UcIvyhLSmyfzbqnl2U37hHGylTDbERM2lMiE5x5EAAjmZjyaBYvEIy+1NzLY6CqfwsErtg2hV26TU/90lRdPKdr6vf240F4hJBZwbXP7GnQRhApx7AOTamfEgBsBfK5HPIJjbUQSWd0a2i97Ej2YVxaDJXLXxjHU5xTGTVR2TynTPCLUKGXkJHXilNj8iq4cUM9zBdW3EkJRkJ5IqBqiHpRK3LZnh4hZ52usjOxMuW2z5b/AejIiUMd+DvTsAVJr4TiKOCgq5Tdqfi9ZqxF06X9yIS2vd8I09e9zc02Tlg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
